// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAkQhDbVF5mGxcdchU-sgfK6iaTXUh2l8',
    appId: '1:619052069020:android:e2fc1bd01b3dbb92e27d59',
    messagingSenderId: '619052069020',
    projectId: 'second-login-ap',
    storageBucket: 'second-login-ap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm92ia1vpiIRapjIKWD5TbRErLEGFVVL8',
    appId: '1:619052069020:ios:94af77531c574b8de27d59',
    messagingSenderId: '619052069020',
    projectId: 'second-login-ap',
    storageBucket: 'second-login-ap.firebasestorage.app',
    iosBundleId: 'com.example.secondAttempt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSbj_vm8jHDKf-7fYxPRPCC4c514UnE6o',
    appId: '1:619052069020:web:f886105f2b83b18de27d59',
    messagingSenderId: '619052069020',
    projectId: 'second-login-ap',
    authDomain: 'second-login-ap.firebaseapp.com',
    storageBucket: 'second-login-ap.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSbj_vm8jHDKf-7fYxPRPCC4c514UnE6o',
    appId: '1:619052069020:web:f886105f2b83b18de27d59',
    messagingSenderId: '619052069020',
    projectId: 'second-login-ap',
    authDomain: 'second-login-ap.firebaseapp.com',
    storageBucket: 'second-login-ap.firebasestorage.app',
  );

}